// === MediaInterface ===
export * from "@/shared/interfaces/mediaInterfaces/Media.interface";
export * from "@/shared/interfaces/mediaInterfaces/Movie.interface";
export * from "@/shared/interfaces/mediaInterfaces/Serie.interface";
// === FilterInterface ===
export * from "@/shared/interfaces/filterInterface/filter.interface";
// === SearchMovieInterface ===
export * from "@/shared/interfaces/searchMovieInterfaces/movieSummary.interface";
export * from "@/shared/interfaces/searchMovieInterfaces/trailer.interface";
export * from "@/shared/interfaces/searchMovieInterfaces/wallpapper.interface";
export * from "@/shared/interfaces/searchMovieInterfaces/movieSimilar.interface";
export * from "@/shared/interfaces/credits.interface";
export * from "@/shared/interfaces/searchMovieInterfaces/moviePages.interface";
// === SerieInterface ===
export * from "@/shared/interfaces/searchSerieInterfaces/seriePages.interface";
export * from "@/shared/interfaces/searchSerieInterfaces/serieSummary.interface";
export * from "@/shared/interfaces/searchSerieInterfaces/serieCredits.interface";
export * from "@/shared/interfaces/searchSerieInterfaces/serieSimilar.interface";
export * from "@/shared/interfaces/searchSerieInterfaces/serieSeason.interface";

// === ActorInterface ===
export * from "@/shared/interfaces/actorInterfaces/actorCredits.interface";
export * from "@/shared/interfaces/actorInterfaces/actorDetails.interface";
export * from "@/shared/interfaces/actorInterfaces/actorImages.interface";
export * from "@/shared/interfaces/actorInterfaces/actorLatest.interface";
export * from "@/shared/interfaces/actorInterfaces/actorPopular.interface";
